import csv

MAP_ID = "map_id"
MAPS_VISITED = "maps_visited"
BLACKOUT = "blackout"
BADGES = "badges"
BADGE_SUM = "badge_sum"
MONEY = "money"
COORDINATES = "coordinates"
PARTY_EXPERIENCE = "party_experience"
TOTAL_EXPERIENCE = "total_experience"
TOTAL_BLACKOUT = "total_blackouts"
PARTY_LEVELS = "party_levels"
TOTAL_LEVELS = "total_levels"
PARTY_HEALTH = "party_health"
PARTY_FILLS = "party_fills"
SEEN_POKEMONS = "seen_pokemons"
CAUGHT_POKEMONS = "caught_pokemons"
EVENTS_TRIGGERED = "events_triggered"
TOTAL_EVENTS_TRIGGERED = "total_events_triggered"
ORIENTATION = "orientation"
SURROUNDING_TILES_VISITATION = "surrounding_tiles_visitation"
NOVELTY_COUNT = "novelty_count"
LEVEL_FRAQ = "level_fraq"
ENTRANCE_DELTA_POS = "entrance_delta_pos"
SENT_OUT = "sent_out"
GOAL_TASK = "goal_task"
IN_BATTLE = "in_battle"
ITEMS = "items"
NUM_BALLS = "num_balls"
NUM_HEALING_ITEMS = "num_healing_items"
NUM_BALLS_USED = "num_balls_used"
NUM_HEALING_ITEMS_USED = "num_healing_items_used"
NUM_BALLS_BOUGHT = "num_balls_bought"
NUM_HEALING_ITEMS_BOUGHT = "num_healing_items_bought"


PKMN_RB_MAPS = {
    0x00 : "Pallet Town",
    0x01 : "Viridian City",
    0x02 : "Pewter City",
    0x03 : "Cerulean City",
    0x04 : "Lavender Town",
    0x05 : "Vermilion City",
    0x06 : "Celadon City",
    0x07 : "Fuchsia City",
    0x08 : "Cinnabar Island",
    0x09 : "Pokémon League",
    0x0A : "Saffron City",
    0x0B : "Unused Fly location",
    0x0C : "Route 1",
    0x0D : "Route 2",
    0x0E : "Route 3",
    0x0F : "Route 4",
    0x10 : "Route 5",
    0x11 : "Route 6",
    0x12 : "Route 7",
    0x13 : "Route 8",
    0x14 : "Route 9",
    0x15 : "Route 10",
    0x16 : "Route 11",
    0x17 : "Route 12",
    0x18 : "Route 13",
    0x19 : "Route 14",
    0x1A : "Route 15",
    0x1B : "Route 16",
    0x1C : "Route 17",
    0x1D : "Route 18",
    0x1E : "Sea Route 19",
    0x1F : "Sea Route 20",
    0x20 : "Sea Route 21",
    0x21 : "Route 22",
    0x22 : "Route 23",
    0x23 : "Route 24",
    0x24 : "Route 25",
    0x25 : "Red's house (first floor)",
    0x26 : "Red's house (second floor)",
    0x27 : "Blue's house",
    0x28 : "Professor Oak's Lab",
    0x29 : "Pokémon Center (Viridian City)",
    0x2A : "Poké Mart (Viridian City)",
    0x2B : "School (Viridian City)",
    0x2C : "House 1 (Viridian City)",
    0x2D : "Gym (Viridian City)",
    0x2E : "Diglett's Cave (Route 2 entrance)",
    0x2F : "Gate (Viridian City/Pewter City) (Route 2)",
    0x30 : "Oak's Aide House 1 (Route 2)",
    0x31 : "Gate (Route 2)",
    0x32 : "Gate (Route 2/Viridian Forest) (Route 2)",
    0x33 : "Viridian Forest",
    0x34 : "Pewter Museum (floor 1)",
    0x35 : "Pewter Museum (floor 2)",
    0x36 : "Gym (Pewter City)",
    0x37 : "House with disobedient Nidoran♂ (Pewter City)",
    0x38 : "Poké Mart (Pewter City)",
    0x39 : "House with two Trainers (Pewter City)",
    0x3A : "Pokémon Center (Pewter City)",
    0x3B : "Mt. Moon (Route 3 entrance)",
    0x3C : "Mt. Moon",
    0x3D : "Mt. Moon",
    0x3E : "Invaded house (Cerulean City)",
    0x3F : "Poliwhirl for Jynx trade house (Red/Blue)",
    0x40 : "Pokémon Center (Cerulean City)",
    0x41 : "Gym (Cerulean City)",
    0x42 : "Bike Shop (Cerulean City)",
    0x43 : "Poké Mart (Cerulean City)",
    0x44 : "Pokémon Center (Route 4)",
    0x45 : "Invaded house - alternative music (Cerulean City)",
    0x46 : "Saffron City Gate (Route 5)",
    0x47 : "Entrance to Underground Path (Route 5)",
    0x48 : "Daycare Center (Route 5)",
    0x49 : "Saffron City Gate (Route 6)",
    0x4A : "Entrance to Underground Path (Route 6)",
    0x4B : "Entrance to Underground Path (alternative music) (Route 6)",
    0x4C : "Saffron City Gate (Route 7)",
    0x4D : "Entrance to Underground Path (Route 7)",
    0x4E : "Entrance to Underground Path (unused) (Route 7)",
    0x4F : "Saffron City Gate (Route 8)",
    0x50 : "Entrance to Underground Path (Route 8)",
    0x51 : "Pokémon Center (Rock Tunnel)",
    0x52 : "Rock Tunnel",
    0x53 : "Power Plant",
    0x54 : "Gate 1F (Route 11-Route 12)",
    0x55 : "Diglett's Cave (Vermilion City entrance)",
    0x56 : "Gate 2F (Route 11-Route 12)",
    0x57 : "Gate (Route 12-Route 13)",
    0x58 : "Sea Cottage",
    0x59 : "Pokémon Center (Vermilion City)",
    0x5A : "Pokémon Fan Club (Vermilion City)",
    0x5B : "Poké Mart (Vermilion City)",
    0x5C : "Gym (Vermilion City)",
    0x5D : "House with Pidgey (Vermilion City)",
    0x5E : "Vermilion Harbor (Vermilion City)",
    0x5F : "S.S. Anne 1F",
    0x60 : "S.S. Anne 2F",
    0x61 : "S.S. Anne 3F",
    0x62 : "S.S. Anne B1F",
    0x63 : "S.S. Anne (Deck)",
    0x64 : "S.S. Anne (Kitchen)",
    0x65 : "S.S. Anne (Captain's room)",
    0x66 : "S.S. Anne 1F (Gentleman's room)",
    0x67 : "S.S. Anne 2F (Gentleman's room)",
    0x68 : "S.S. Anne B1F (Sailor/Fisherman's room)",
    0x69 : "Unused (Victory Road)",
    0x6A : "Unused (Victory Road)",
    0x6B : "Unused (Victory Road)",
    0x6C : "Victory Road (Route 23 entrance)",
    0x6D : "Unused (Pokémon League)",
    0x6E : "Unused (Pokémon League)",
    0x6F : "Unused (Pokémon League)",
    0x70 : "Unused (Pokémon League)",
    0x71 : "Lance's Elite Four room",
    0x72 : "Unused (Pokémon League)",
    0x73 : "Unused (Pokémon League)",
    0x74 : "Unused (Pokémon League)",
    0x75 : "Unused (Pokémon League)",
    0x76 : "Hall of Fame",
    0x77 : "Underground Path (Route 5-Route 6)",
    0x78 : "Blue (Champion)'s room",
    0x79 : "Underground Path (Route 7-Route 8)",
    0x7A : "Celadon Department Store 1F",
    0x7B : "Celadon Department Store 2F",
    0x7C : "Celadon Department Store 3F",
    0x7D : "Celadon Department Store 4F",
    0x7E : "Celadon Department Store Rooftop Square",
    0x7F : "Celadon Department Store Lift",
    0x80 : "Celadon Mansion 1F",
    0x81 : "Celadon Mansion 2F",
    0x82 : "Celadon Mansion 3F",
    0x83 : "Celadon Mansion 4F",
    0x84 : "Celadon Mansion 4F (Eevee building)",
    0x85 : "Pokémon Center (Celadon City)",
    0x86 : "Gym (Celadon City)",
    0x87 : "Rocket Game Corner (Celadon City)",
    0x88 : "Celadon Department Store 5F",
    0x89 : "Prize corner (Celadon City)",
    0x8A : "Restaurant (Celadon City)",
    0x8B : "House with Team Rocket members (Celadon City)",
    0x8C : "Hotel (Celadon City)",
    0x8D : "Pokémon Center (Lavender Town)",
    0x8E : "Pokémon Tower 1F",
    0x8F : "Pokémon Tower 2F",
    0x90 : "Pokémon Tower 3F",
    0x91 : "Pokémon Tower 4F",
    0x92 : "Pokémon Tower 5F",
    0x93 : "Pokémon Tower 6F",
    0x94 : "Pokémon Tower 7F",
    0x95 : "Mr. Fuji's house (Lavender Town)",
    0x96 : "Poké Mart (Lavender Town)",
    0x97 : "House with NPC discussing Cubone's mother",
    0x98 : "Poké Mart (Fuchsia City)",
    0x99 : "House with NPCs discussing Bill (Fuchsia City)",
    0x9A : "Pokémon Center (Fuchsia City)",
    0x9B : "Warden's house (Fuchsia City)",
    0x9C : "Safari Zone gate (Fuchsia City)",
    0x9D : "Gym (Fuchsia City)",
    0x9E : "House with NPCs discussing Baoba (Fuchsia City)",
    0x9F : "Seafoam Islands",
    0xA0 : "Seafoam Islands",
    0xA1 : "Seafoam Islands",
    0xA2 : "Seafoam Islands",
    0xA3 : "Vermilion City Fishing Brother",
    0xA4 : "Fuchsia City Fishing Brother",
    0xA5 : "Pokémon Mansion (1F)",
    0xA6 : "Gym (Cinnabar Island)",
    0xA7 : "Pokémon Lab (Cinnabar Island)",
    0xA8 : "Pokémon Lab - Trade room (Cinnabar Island)",
    0xA9 : "Pokémon Lab - Room with scientists (Cinnabar Island)",
    0xAA : "Pokémon Lab - Fossil resurrection room (Cinnabar Island)",
    0xAB : "Pokémon Center (Cinnabar Island)",
    0xAC : "Poké Mart (Cinnabar Island)",
    0xAD : "Poké Mart - alternative music (Cinnabar Island)",
    0xAE : "Pokémon Center (Indigo Plateau)",
    0xAF : "Copycat's house 1F (Saffron City)",
    0xB0 : "Copycat's house 2F (Saffron City)",
    0xB1 : "Fighting Dojo (Saffron City)",
    0xB2 : "Gym (Saffron City)",
    0xB3 : "House with Pidgey (Saffron City)",
    0xB4 : "Poké Mart (Saffron City)",
    0xB5 : "Silph Co. 1F",
    0xB6 : "Pokémon Center (Saffron City)",
    0xB7 : "Mr. Psychic's house (Saffron City)",
    0xB8 : "Gate 1F (Route 15)",
    0xB9 : "Gate 2F (Route 15)",
    0xBA : "Gate 1F (Cycling Road) (Route 16)",
    0xBB : "Gate 2F (Cycling Road) (Route 16)",
    0xBC : "Secret house (Cycling Road) (Route 16)",
    0xBD : "Route 12 Fishing Brother",
    0xBE : "Gate 1F (Route 18)",
    0xBF : "Gate 2F (Route 18)",
    0xC0 : "Seafoam Islands",
    0xC1 : "Badges check gate (Route 22)",
    0xC2 : "Victory Road",
    0xC3 : "Gate 2F (Route 12)",
    0xC4 : "House with NPC and HM moves advice (Vermilion City)",
    0xC5 : "Diglett's Cave",
    0xC6 : "Victory Road",
    0xC7 : "Team Rocket Hideout (B1F)",
    0xC8 : "Team Rocket Hideout (B2F)",
    0xC9 : "Team Rocket Hideout (B3F)",
    0xCA : "Team Rocket Hideout (B4F)",
    0xCB : "Team Rocket Hideout (Lift)",
    0xCC : "Unused (Team Rocket Hideout)",
    0xCD : "Unused (Team Rocket Hideout)",
    0xCE : "Unused (Team Rocket Hideout)",
    0xCF : "Silph Co. (2F)",
    0xD0 : "Silph Co. (3F)",
    0xD1 : "Silph Co. (4F)",
    0xD2 : "Silph Co. (5F)",
    0xD3 : "Silph Co. (6F)",
    0xD4 : "Silph Co. (7F)",
    0xD5 : "Silph Co. (8F)",
    0xD6 : "Pokémon Mansion (2F)",
    0xD7 : "Pokémon Mansion (3F)",
    0xD8 : "Pokémon Mansion (B1F)",
    0xD9 : "Safari Zone (Area 1)",
    0xDA : "Safari Zone (Area 2)",
    0xDB : "Safari Zone (Area 3)",
    0xDC : "Safari Zone (Entrance)",
    0xDD : "Safari Zone (Rest house 1)",
    0xDE : "Safari Zone (Prize house)",
    0xDF : "Safari Zone (Rest house 2)",
    0xE0 : "Safari Zone (Rest house 3)",
    0xE1 : "Safari Zone (Rest house 4)",
    0xE2 : "Cerulean Cave",
    0xE3 : "Cerulean Cave 1F",
    0xE4 : "Cerulean Cave B1F",
    0xE5 : "Name Rater's house (Lavender Town)",
    0xE6 : "Cerulean City (Gym Badge man)",
    0xE7 : "Unused (Rock Tunnel)",
    0xE8 : "Rock Tunnel",
    0xE9 : "Silph Co. 9F",
    0xEA : "Silph Co. 10F",
    0xEB : "Silph Co. 11F",
    0xEC : "Silph Co. Lift",
    0xED : "(Invalid)",
    0xEE : "(Invalid)",
    0xEF : "Cable Club Trade Center(*)",
    0xF0 : "Cable Club Colosseum(*)",
    0xF1 : "(Invalid)",
    0xF2 : "(Invalid)",
    0xF3 : "(Invalid)",
    0xF4 : "(Invalid)",
    0xF5 : "Lorelei's room",
    0xF6 : "Bruno's room",
    0xF7 : "Agatha's room",
}
